version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb2
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

  clientes:
    build: .
    container_name: clientes
    ports:
      - "5001:5001"
    depends_on:
      - mongo

volumes:
  mongo-data: